from typing import TypedDict

from langchain_core.documents import Document


class GraphState(TypedDict):
    """
    Shared state passed between LangGraph nodes.

    The original question is preserved throughout the graph.
    Retrieval can operate on a rewritten search_query.
    """

    # Original user question.
    # This should never be modified by query rewriting.
    question: str

    # Query currently being used for retrieval.
    # This can be changed by the rewrite node.
    search_query: str

    # Documents retrieved during the current retrieval attempt.
    documents: list[Document]

    # Documents judged relevant by the grader.
    relevant_documents: list[Document]

    # Whether the retrieved evidence is sufficient to answer
    # the original question.
    sufficient: bool

    # Explanation produced by the document grader.
    grade_reason: str

    # Number of query rewrites already performed.
    rewrite_count: int

    # Final answer generated by the LLM or fallback node.
    answer: str

    # Whether the system successfully answered the question.
    answered: bool